- name: Install Nagios for Ubuntu
  apt:
    name:
      - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Nagios for CentOS
  yum:
    name: 
      - nagios
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
