- name: Install Nagios Monitoring Service in Ubuntu
  apt:
    name: nagios4
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Nagios Monitoring Service in CentOS
  yum:
    name: nagios
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"
